### ISSUE TITLE
Why do another train_test_split?

### ISSUE THREAD

**Issue by jmrichardson** [atif-hassan/PyImpetus#13]
In your main fit, it appears that you are splitting the data into train/test but sending just the train split to self._find_MB:

`tmp = parallel(delayed(self._find_MB)(data.iloc[train].copy(), Y[train]) for train, test in self.cv.split(data))`

But in _feature_importance method, you are doing another train_test_split on the training data.  Why wouldn't you use the test data from split above?  It doesn't appear the test data from the self.cv.split is being used at all for testing?

**Comment by atif-hassan** [comment]
Hey!

We perform a train-test split in the main fit method on the training data so that we can generate different Markov Blankets. The idea is to look at different MBs and report the MB having the highest score.

In each such split we need to perform further splits in order for the PPI test to work. You can get an idea from the ArXiv paper available here: https://arxiv.org/abs/2110.10713
